// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LocalInternalAIChatBot.Web.Models;

public partial class ArticleVectorDatum
{
    public int Id { get; set; }

    public int ArticleDetailId { get; set; }

    public int VectorValueId { get; set; }

    public double VectorValue { get; set; }

    public virtual ArticleDetail ArticleDetail { get; set; }
}